# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_to_col <- function(cell) {
    .Call(`_openxlsx2_int_to_col`, cell)
}

col_to_int <- function(x) {
    .Call(`_openxlsx2_col_to_int`, x)
}

rbindlist <- function(x) {
    .Call(`_openxlsx2_rbindlist`, x)
}

long_to_wide <- function(z, tt, zz) {
    invisible(.Call(`_openxlsx2_long_to_wide`, z, tt, zz))
}

wide_to_long <- function(z, vtyps, zz, ColNames, start_col, start_row) {
    invisible(.Call(`_openxlsx2_wide_to_long`, z, vtyps, zz, ColNames, start_col, start_row))
}

#' @import Rcpp
NULL

col_to_df <- function(doc) {
    .Call(`_openxlsx2_col_to_df`, doc)
}

df_to_xml <- function(name, df_col) {
    .Call(`_openxlsx2_df_to_xml`, name, df_col)
}

loadvals <- function(sheet_data, doc) {
    invisible(.Call(`_openxlsx2_loadvals`, sheet_data, doc))
}

si_to_txt <- function(doc) {
    .Call(`_openxlsx2_si_to_txt`, doc)
}

is_to_txt <- function(is_vec) {
    .Call(`_openxlsx2_is_to_txt`, is_vec)
}

readXMLPtr <- function(path, isfile, escapes, declaration) {
    .Call(`_openxlsx2_readXMLPtr`, path, isfile, escapes, declaration)
}

readXML <- function(path, isfile, escapes, declaration) {
    .Call(`_openxlsx2_readXML`, path, isfile, escapes, declaration)
}

getXMLXPtrName <- function(doc) {
    .Call(`_openxlsx2_getXMLXPtrName`, doc)
}

getXMLXPtr0 <- function(doc) {
    .Call(`_openxlsx2_getXMLXPtr0`, doc)
}

getXMLXPtr1 <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1`, doc, child)
}

getXMLXPtr2 <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2`, doc, level1, child)
}

getXMLXPtr3 <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3`, doc, level1, level2, child)
}

unkgetXMLXPtr3 <- function(doc, level1, child) {
    .Call(`_openxlsx2_unkgetXMLXPtr3`, doc, level1, child)
}

getXMLXPtr4 <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4`, doc, level1, level2, level3, child)
}

getXMLXPtr1val <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1val`, doc, child)
}

getXMLXPtr2val <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2val`, doc, level1, child)
}

getXMLXPtr3val <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3val`, doc, level1, level2, child)
}

getXMLXPtr4val <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4val`, doc, level1, level2, level3, child)
}

setXMLXPtr1val <- function(doc, child, value, no_escapes, raw) {
    .Call(`_openxlsx2_setXMLXPtr1val`, doc, child, value, no_escapes, raw)
}

setXMLXPtr2val <- function(doc, level1, child, value, no_escapes, raw) {
    .Call(`_openxlsx2_setXMLXPtr2val`, doc, level1, child, value, no_escapes, raw)
}

setXMLXPtr3val <- function(doc, level1, level2, child, value, no_escapes, raw) {
    .Call(`_openxlsx2_setXMLXPtr3val`, doc, level1, level2, child, value, no_escapes, raw)
}

setXMLXPtr4val <- function(doc, level1, level2, level3, child, value, no_escapes, raw) {
    .Call(`_openxlsx2_setXMLXPtr4val`, doc, level1, level2, level3, child, value, no_escapes, raw)
}

getXMLXPtr1attr <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1attr`, doc, child)
}

getXMLXPtr2attr <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2attr`, doc, level1, child)
}

getXMLXPtr3attr <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3attr`, doc, level1, level2, child)
}

getXMLXPtr4attr <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4attr`, doc, level1, level2, level3, child)
}

printXPtr <- function(doc, no_escapes, raw) {
    .Call(`_openxlsx2_printXPtr`, doc, no_escapes, raw)
}

write_xml_file <- function(xml_content, fl, escapes) {
    invisible(.Call(`_openxlsx2_write_xml_file`, xml_content, fl, escapes))
}

#' adds or updates attribute(s) in existing xml node
#'
#' @description Needs xml node and named character vector as input. Modifies
#' the arguments of each first child found in the xml node and adds or updates
#' the attribute vector.
#' @details If a named attribute in `xml_attributes` is "" remove the attribute
#' from the node.
#' If `xml_attributes` contains a named entry found in the xml node, it is
#' updated else it is added as attribute.
#'
#' @param xml_content some valid xml_node
#' @param xml_attributes R vector of named attributes
#' @param escapes bool if escapes should be used
#' @param declaration bool if declaration should be imported
#'
#' @examples
#'   # add single node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(qux = "quux")
#'     # "<a foo=\"bar\" qux=\"quux\">openxlsx2</a><b qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#'
#'   # update node and add node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(foo = "baz", qux = "quux")
#'     # "<a foo=\"baz\" qux=\"quux\">openxlsx2</a><b foo=\"baz\" qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#'
#'   # remove node and add node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(foo = "", qux = "quux")
#'     # "<a qux=\"quux\">openxlsx2</a><b qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#' @export
xml_attr_mod <- function(xml_content, xml_attributes, escapes = FALSE, declaration = FALSE) {
    .Call(`_openxlsx2_xml_attr_mod`, xml_content, xml_attributes, escapes, declaration)
}

#' create xml_node from R objects
#' @description takes xml_name, xml_children and xml_attributes to create a new
#' xml_node.
#' @param xml_name the name of the new xml_node
#' @param xml_children character vector children attached to the xml_node
#' @param xml_attributes named character vector of attributes for the xml_node
#' @param escapes bool if escapes should be used
#' @param declaration bool if declaration should be imported
#' @details if xml_children or xml_attributes should be empty, use NULL
#'
#' @examples
#' xml_name <- "a"
#' # "<a/>"
#' xml_node_create(xml_name)
#'
#' xml_child <- "openxlsx"
#' # "<a>openxlsx</a>"
#' xml_node_create(xml_name, xml_children = xml_child)
#'
#' xml_attr <- c(foo = "baz", qux = "quux")
#' # "<a foo=\"baz\" qux=\"quux\"/>"
#' xml_node_create(xml_name, xml_attributes = xml_attr)
#'
#' # "<a foo=\"baz\" qux=\"quux\">openxlsx</a>"
#' xml_node_create(xml_name, xml_children = xml_child, xml_attributes = xml_attr)
#' @export
xml_node_create <- function(xml_name, xml_children = NULL, xml_attributes = NULL, escapes = FALSE, declaration = FALSE) {
    .Call(`_openxlsx2_xml_node_create`, xml_name, xml_children, xml_attributes, escapes, declaration)
}

xml_append_child <- function(node, child, pointer, escapes) {
    .Call(`_openxlsx2_xml_append_child`, node, child, pointer, escapes)
}

read_xf <- function(xml_doc_xf) {
    .Call(`_openxlsx2_read_xf`, xml_doc_xf)
}

write_xf <- function(df_xf) {
    .Call(`_openxlsx2_write_xf`, df_xf)
}

read_font <- function(xml_doc_font) {
    .Call(`_openxlsx2_read_font`, xml_doc_font)
}

write_font <- function(df_font) {
    .Call(`_openxlsx2_write_font`, df_font)
}

read_numfmt <- function(xml_doc_numfmt) {
    .Call(`_openxlsx2_read_numfmt`, xml_doc_numfmt)
}

write_numfmt <- function(df_numfmt) {
    .Call(`_openxlsx2_write_numfmt`, df_numfmt)
}

read_border <- function(xml_doc_border) {
    .Call(`_openxlsx2_read_border`, xml_doc_border)
}

write_border <- function(df_border) {
    .Call(`_openxlsx2_write_border`, df_border)
}

read_fill <- function(xml_doc_fill) {
    .Call(`_openxlsx2_read_fill`, xml_doc_fill)
}

write_fill <- function(df_fill) {
    .Call(`_openxlsx2_write_fill`, df_fill)
}

read_cellStyle <- function(xml_doc_cellStyle) {
    .Call(`_openxlsx2_read_cellStyle`, xml_doc_cellStyle)
}

write_cellStyle <- function(df_cellstyle) {
    .Call(`_openxlsx2_write_cellStyle`, df_cellstyle)
}

read_tableStyle <- function(xml_doc_tableStyle) {
    .Call(`_openxlsx2_read_tableStyle`, xml_doc_tableStyle)
}

write_tableStyle <- function(df_tablestyle) {
    .Call(`_openxlsx2_write_tableStyle`, df_tablestyle)
}

read_dxf <- function(xml_doc_dxf) {
    .Call(`_openxlsx2_read_dxf`, xml_doc_dxf)
}

write_dxf <- function(df_dxf) {
    .Call(`_openxlsx2_write_dxf`, df_dxf)
}

read_colors <- function(xml_doc_colors) {
    .Call(`_openxlsx2_read_colors`, xml_doc_colors)
}

write_colors <- function(df_colors) {
    .Call(`_openxlsx2_write_colors`, df_colors)
}

build_cell_merges <- function(comps) {
    .Call(`_openxlsx2_build_cell_merges`, comps)
}

set_sst <- function(sharedStrings) {
    .Call(`_openxlsx2_set_sst`, sharedStrings)
}

write_worksheet_xml_2 <- function(prior, post, sheet_data, cols_attr, R_fileName = "output") {
    .Call(`_openxlsx2_write_worksheet_xml_2`, prior, post, sheet_data, cols_attr, R_fileName)
}

