# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readXML <- function(path, isfile, declaration) {
    .Call(`_openxlsx2_readXML`, path, isfile, declaration)
}

getXML1 <- function(str, child) {
    .Call(`_openxlsx2_getXML1`, str, child)
}

getXML1val <- function(str, child) {
    .Call(`_openxlsx2_getXML1val`, str, child)
}

getXML2 <- function(str, level1, child) {
    .Call(`_openxlsx2_getXML2`, str, level1, child)
}

getXML2val <- function(str, level1, child) {
    .Call(`_openxlsx2_getXML2val`, str, level1, child)
}

getXML3 <- function(str, level1, level2, child) {
    .Call(`_openxlsx2_getXML3`, str, level1, level2, child)
}

getXML3val <- function(str, level1, level2, child) {
    .Call(`_openxlsx2_getXML3val`, str, level1, level2, child)
}

getXMLattr <- function(strs, child) {
    .Call(`_openxlsx2_getXMLattr`, strs, child)
}

getXML1attr_one <- function(str, child, attr) {
    .Call(`_openxlsx2_getXML1attr_one`, str, child, attr)
}

calc_column_widths <- function(sheet_data, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW) {
    .Call(`_openxlsx2_calc_column_widths`, sheet_data, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW)
}

convert_to_excel_ref <- function(cols, LETTERS) {
    .Call(`_openxlsx2_convert_to_excel_ref`, cols, LETTERS)
}

convert_from_excel_ref <- function(x) {
    .Call(`_openxlsx2_convert_from_excel_ref`, x)
}

convert_to_excel_ref_expand <- function(cols, LETTERS, rows) {
    .Call(`_openxlsx2_convert_to_excel_ref_expand`, cols, LETTERS, rows)
}

get_letters <- function() {
    .Call(`_openxlsx2_get_letters`)
}

rbindlist <- function(x) {
    .Call(`_openxlsx2_rbindlist`, x)
}

#' @import Rcpp
NULL

col_to_df <- function(doc) {
    .Call(`_openxlsx2_col_to_df`, doc)
}

df_to_col <- function(df_col) {
    .Call(`_openxlsx2_df_to_col`, df_col)
}

loadvals <- function(wb, doc) {
    invisible(.Call(`_openxlsx2_loadvals`, wb, doc))
}

si_to_txt <- function(doc) {
    .Call(`_openxlsx2_si_to_txt`, doc)
}

is_to_txt <- function(is_vec) {
    .Call(`_openxlsx2_is_to_txt`, is_vec)
}

long_to_wide <- function(z, tt, zz) {
    invisible(.Call(`_openxlsx2_long_to_wide`, z, tt, zz))
}

cell_ref_to_col <- function(x) {
    .Call(`_openxlsx2_cell_ref_to_col`, x)
}

int_2_cell_ref <- function(cols) {
    .Call(`_openxlsx2_int_2_cell_ref`, cols)
}

readXMLPtr <- function(path, isfile, declaration) {
    .Call(`_openxlsx2_readXMLPtr`, path, isfile, declaration)
}

getXMLXPtr1 <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1`, doc, child)
}

getXMLXPtr2 <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2`, doc, level1, child)
}

getXMLXPtr3 <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3`, doc, level1, level2, child)
}

unkgetXMLXPtr3 <- function(doc, level1, child) {
    .Call(`_openxlsx2_unkgetXMLXPtr3`, doc, level1, child)
}

getXMLXPtr4 <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4`, doc, level1, level2, level3, child)
}

getXMLXPtr5 <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx2_getXMLXPtr5`, doc, level1, level2, level3, level4, child)
}

getXMLXPtr1val <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1val`, doc, child)
}

getXMLXPtr2val <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2val`, doc, level1, child)
}

getXMLXPtr3val <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3val`, doc, level1, level2, child)
}

getXMLXPtr4val <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4val`, doc, level1, level2, level3, child)
}

getXMLXPtr5val <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx2_getXMLXPtr5val`, doc, level1, level2, level3, level4, child)
}

getXMLXPtr1attr <- function(doc, child) {
    .Call(`_openxlsx2_getXMLXPtr1attr`, doc, child)
}

getXMLXPtr2attr <- function(doc, level1, child) {
    .Call(`_openxlsx2_getXMLXPtr2attr`, doc, level1, child)
}

getXMLXPtr3attr <- function(doc, level1, level2, child) {
    .Call(`_openxlsx2_getXMLXPtr3attr`, doc, level1, level2, child)
}

getXMLXPtr4attr <- function(doc, level1, level2, level3, child) {
    .Call(`_openxlsx2_getXMLXPtr4attr`, doc, level1, level2, level3, child)
}

getXMLXPtr5attr <- function(doc, level1, level2, level3, level4, child) {
    .Call(`_openxlsx2_getXMLXPtr5attr`, doc, level1, level2, level3, level4, child)
}

getXMLXPtr1attr_one <- function(doc, child, attrname) {
    .Call(`_openxlsx2_getXMLXPtr1attr_one`, doc, child, attrname)
}

getXMLXPtr2attr_one <- function(doc, level1, child, attrname) {
    .Call(`_openxlsx2_getXMLXPtr2attr_one`, doc, level1, child, attrname)
}

getXMLXPtr3attr_one <- function(doc, level1, level2, child, attrname) {
    .Call(`_openxlsx2_getXMLXPtr3attr_one`, doc, level1, level2, child, attrname)
}

getXMLXPtr4attr_one <- function(doc, level1, level2, level3, child, attrname) {
    .Call(`_openxlsx2_getXMLXPtr4attr_one`, doc, level1, level2, level3, child, attrname)
}

font_val <- function(fonts, level3, child) {
    .Call(`_openxlsx2_font_val`, fonts, level3, child)
}

style_xml_as_list <- function(xml_input, level3) {
    .Call(`_openxlsx2_style_xml_as_list`, xml_input, level3)
}

printXPtr <- function(doc, raw) {
    .Call(`_openxlsx2_printXPtr`, doc, raw)
}

write_xml_file <- function(xml_content, fl) {
    invisible(.Call(`_openxlsx2_write_xml_file`, xml_content, fl))
}

#' adds or updates attribute(s) in existing xml node
#'
#' @description Needs xml node and named character vector as input. Modifies
#' the argutments of each first child found in the xml node and adds or updates
#' the attribute vector.
#' @details If a named attribute in `xml_attributes` is "" remove the attribute
#' from the node.
#' If `xml_attributes` contains a named entry found in the xml node, it is
#' updated else it is added as attribute.
#'
#' @param xml_content some valid xml_node
#' @param xml_attributes R vector of named attributes
#'
#' @examples
#'   # add single node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(qux = "quux")
#'     # "<a foo=\"bar\" qux=\"quux\">openxlsx2</a><b qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#'
#'   # update node and add node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(foo = "baz", qux = "quux")
#'     # "<a foo=\"baz\" qux=\"quux\">openxlsx2</a><b foo=\"baz\" qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#'
#'   # remove node and add node
#'     xml_node <- "<a foo=\"bar\">openxlsx2</a><b />"
#'     xml_attr <- c(foo = "", qux = "quux")
#'     # "<a qux=\"quux\">openxlsx2</a><b qux=\"quux\"/>"
#'     xml_attr_mod(xml_node, xml_attr)
#' @export
xml_attr_mod <- function(xml_content, xml_attributes) {
    .Call(`_openxlsx2_xml_attr_mod`, xml_content, xml_attributes)
}

#' create xml_node from R objects
#' @description takes xml_name, xml_children and xml_attributes to create a new
#' xml_node.
#' @param xml_name the name of the new xml_node
#' @param xml_children character vector children attached to the xml_node
#' @param xml_attributes named character vector of attributes for the xml_node
#' @details if xml_children or xml_attributes should be empty, use NULL
#'
#' @examples
#' xml_name <- "a"
#' # "<a/>"
#' xml_node_create(xml_name)
#'
#' xml_child <- "openxlsx"
#' # "<a>openxlsx</a>"
#' xml_node_create(xml_name, xml_children = xml_child)
#'
#' xml_attr <- c(foo = "baz", qux = "quux")
#' # "<a foo=\"baz\" qux=\"quux\"/>"
#' xml_node_create(xml_name, xml_attributes = xml_attr)
#'
#' # "<a foo=\"baz\" qux=\"quux\">openxlsx</a>"
#' xml_node_create(xml_name, xml_children = xml_child, xml_attributes = xml_attr)
#' @export
xml_node_create <- function(xml_name, xml_children = NULL, xml_attributes = NULL) {
    .Call(`_openxlsx2_xml_node_create`, xml_name, xml_children, xml_attributes)
}

xml_append_child <- function(node, child, pointer) {
    .Call(`_openxlsx2_xml_append_child`, node, child, pointer)
}

set_sst <- function(sharedStrings) {
    .Call(`_openxlsx2_set_sst`, sharedStrings)
}

list_to_attr <- function(attributes, node) {
    .Call(`_openxlsx2_list_to_attr`, attributes, node)
}

list_to_attr_full <- function(attributes, node, child) {
    .Call(`_openxlsx2_list_to_attr_full`, attributes, node, child)
}

read_xf <- function(xml_doc_xf) {
    .Call(`_openxlsx2_read_xf`, xml_doc_xf)
}

write_xf <- function(df_xf) {
    .Call(`_openxlsx2_write_xf`, df_xf)
}

read_font <- function(xml_doc_font) {
    .Call(`_openxlsx2_read_font`, xml_doc_font)
}

write_font <- function(df_font) {
    .Call(`_openxlsx2_write_font`, df_font)
}

read_numfmt <- function(xml_doc_numfmt) {
    .Call(`_openxlsx2_read_numfmt`, xml_doc_numfmt)
}

write_numfmt <- function(df_numfmt) {
    .Call(`_openxlsx2_write_numfmt`, df_numfmt)
}

read_border <- function(xml_doc_border) {
    .Call(`_openxlsx2_read_border`, xml_doc_border)
}

write_border <- function(df_border) {
    .Call(`_openxlsx2_write_border`, df_border)
}

read_fill <- function(xml_doc_fill) {
    .Call(`_openxlsx2_read_fill`, xml_doc_fill)
}

write_fill <- function(df_fill) {
    .Call(`_openxlsx2_write_fill`, df_fill)
}

read_cellStyle <- function(xml_doc_cellStyle) {
    .Call(`_openxlsx2_read_cellStyle`, xml_doc_cellStyle)
}

write_cellStyle <- function(df_cellstyle) {
    .Call(`_openxlsx2_write_cellStyle`, df_cellstyle)
}

read_tableStyle <- function(xml_doc_tableStyle) {
    .Call(`_openxlsx2_read_tableStyle`, xml_doc_tableStyle)
}

write_tableStyle <- function(df_tablestyle) {
    .Call(`_openxlsx2_write_tableStyle`, df_tablestyle)
}

read_dxf <- function(xml_doc_dxf) {
    .Call(`_openxlsx2_read_dxf`, xml_doc_dxf)
}

write_dxf <- function(df_dxf) {
    .Call(`_openxlsx2_write_dxf`, df_dxf)
}

read_colors <- function(xml_doc_colors) {
    .Call(`_openxlsx2_read_colors`, xml_doc_colors)
}

write_colors <- function(df_colors) {
    .Call(`_openxlsx2_write_colors`, df_colors)
}

build_cell_types_integer <- function(classes, n_rows) {
    .Call(`_openxlsx2_build_cell_types_integer`, classes, n_rows)
}

build_cell_merges <- function(comps) {
    .Call(`_openxlsx2_build_cell_merges`, comps)
}

set_row <- function(row_attr, cells, row_idx) {
    .Call(`_openxlsx2_set_row`, row_attr, cells, row_idx)
}

write_worksheet_xml_2 <- function(prior, post, sheet_data, cols_attr, R_fileName = "output") {
    .Call(`_openxlsx2_write_worksheet_xml_2`, prior, post, sheet_data, cols_attr, R_fileName)
}

